-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 10:26:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cul_dampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cul_dampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cul_dampolla` DEFAULT CHARACTER SET utf8 ;
USE `cul_dampolla` ;

-- -----------------------------------------------------
-- Table `cul_dampolla`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`proveidor` (
  `name` VARCHAR(30) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `nif` VARCHAR(10) NOT NULL,
  `proveidorId` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  PRIMARY KEY (`proveidorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `proveidorId` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca`),
  CONSTRAINT `marcas`
    FOREIGN KEY ()
    REFERENCES `cul_dampolla`.`proveidor` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`ulleres` (
  `marca` INT NOT NULL,
  `grad_Left` FLOAT(4,2) NULL,
  `grad_Right` FLOAT(4,2) NULL,
  `model` ENUM('flotante', 'metalica', 'pasta') NOT NULL,
  `color` VARCHAR(15) NOT NULL,
  `glass_color_left` VARCHAR(15) NULL,
  `glass_color_ritgth` VARCHAR(15) NULL,
  `price` FLOAT(6,2) NOT NULL,
  `idClient` INT(8) NULL,
  `employeId` INT NULL,
  `idulleres` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idulleres`),
  INDEX `marca_idx` (`marca` ASC) VISIBLE,
  CONSTRAINT `marca`
    FOREIGN KEY (`marca`)
    REFERENCES `cul_dampolla`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`clients` (
  `clientId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `regdate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `recomendedBy` INT NULL,
  PRIMARY KEY (`clientId`),
  INDEX `recomended_idx` (`recomendedBy` ASC) VISIBLE,
  CONSTRAINT `recomended`
    FOREIGN KEY (`recomendedBy`)
    REFERENCES `cul_dampolla`.`clients` (`clientId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`employe` (
  `name` VARCHAR(45) NOT NULL,
  `idEmploye` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idEmploye`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `employeId` INT NULL,
  `clientId` INT NULL,
  `ulleresId` INT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `venta_idx` (`ulleresId` ASC) VISIBLE,
  INDEX `sellBy_idx` (`employeId` ASC) VISIBLE,
  INDEX `compras_idx` (`clientId` ASC) VISIBLE,
  CONSTRAINT `venta`
    FOREIGN KEY (`ulleresId`)
    REFERENCES `cul_dampolla`.`ulleres` (`idulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sellBy`
    FOREIGN KEY (`employeId`)
    REFERENCES `cul_dampolla`.`employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `compras`
    FOREIGN KEY (`clientId`)
    REFERENCES `cul_dampolla`.`clients` (`clientId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
