-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 13:30:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincia` (
  `idprovincia` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprovincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`localitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localitat` (
  `idLocalitat` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `provinciaId` INT NULL,
  PRIMARY KEY (`idLocalitat`),
  INDEX `provinciaId_idx` (`provinciaId` ASC) VISIBLE,
  CONSTRAINT `provinciaId`
    FOREIGN KEY (`provinciaId`)
    REFERENCES `pizzeria`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`costumers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`costumers` (
  `idcostumers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(10) NOT NULL,
  `localitatId` INT NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idcostumers`),
  INDEX `localitatId_idx` (`localitatId` ASC) VISIBLE,
  CONSTRAINT `localitatIdcostumer`
    FOREIGN KEY (`localitatId`)
    REFERENCES `pizzeria`.`localitat` (`idLocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`store` (
  `idstore` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(10) NULL,
  `localitatId` INT NULL,
  PRIMARY KEY (`idstore`),
  INDEX `localitatId_idx` (`localitatId` ASC) VISIBLE,
  CONSTRAINT `localitatId`
    FOREIGN KEY (`localitatId`)
    REFERENCES `pizzeria`.`localitat` (`idLocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` ENUM('shipment', 'collect') NOT NULL,
  `numProducts` INT NOT NULL,
  `totalPrice` DECIMAL(4,2) NOT NULL,
  `storeId` INT NOT NULL,
  `costumerId` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `storeId_idx` (`storeId` ASC) VISIBLE,
  INDEX `costumerIdOrder_idx` (`costumerId` ASC) VISIBLE,
  CONSTRAINT `storeId`
    FOREIGN KEY (`storeId`)
    REFERENCES `pizzeria`.`store` (`idstore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `costumerIdOrder`
    FOREIGN KEY (`costumerId`)
    REFERENCES `pizzeria`.`costumers` (`idcostumers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`employee` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(12) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `rol` ENUM('chef', 'raider') NOT NULL,
  `storeId` INT NULL,
  PRIMARY KEY (`idemployee`),
  INDEX `storeId_idx` (`storeId` ASC) VISIBLE,
  CONSTRAINT `storeIdemployee`
    FOREIGN KEY (`storeId`)
    REFERENCES `pizzeria`.`store` (`idstore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`shipment` (
  `idshipment` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT NULL,
  `costumerId` INT NULL,
  `riderId` INT NOT NULL,
  PRIMARY KEY (`idshipment`),
  INDEX `orderId_idx` (`orderId` ASC) VISIBLE,
  INDEX `costumerId_idx` (`costumerId` ASC) VISIBLE,
  INDEX `fk_shipment_employee1_idx` (`riderId` ASC) VISIBLE,
  CONSTRAINT `idOrderShipment`
    FOREIGN KEY (`orderId`)
    REFERENCES `pizzeria`.`order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `costumerId`
    FOREIGN KEY (`costumerId`)
    REFERENCES `pizzeria`.`costumers` (`idcostumers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipment_employee1`
    FOREIGN KEY (`riderId`)
    REFERENCES `pizzeria`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` TEXT(200) NULL,
  `image` VARCHAR(45) NULL,
  `price` FLOAT NOT NULL,
  `class` ENUM('pizza', 'hamburguer', 'drink') NOT NULL,
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizzaCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizzaCategory` (
  `idpizzaCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpizzaCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizza` (
  `idpizza` INT NOT NULL AUTO_INCREMENT,
  `categoryId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `productId` INT NOT NULL,
  PRIMARY KEY (`idpizza`),
  INDEX `productId_idx` (`productId` ASC) VISIBLE,
  INDEX `categoryId_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `productId`
    FOREIGN KEY (`productId`)
    REFERENCES `pizzeria`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoryId`
    FOREIGN KEY (`categoryId`)
    REFERENCES `pizzeria`.`pizzaCategory` (`idpizzaCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`cart` (
  `idcart` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NOT NULL,
  `orderId` INT NOT NULL,
  `unityProduct` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcart`),
  INDEX `orderId_idx` (`orderId` ASC) VISIBLE,
  INDEX `productId_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `orderId`
    FOREIGN KEY (`orderId`)
    REFERENCES `pizzeria`.`order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productIdcart`
    FOREIGN KEY (`productId`)
    REFERENCES `pizzeria`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
